[package]
name = "malbox-controller"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "malbox"
path = "src/main.rs"

[dependencies]
malbox-proto = { path = "../malbox-proto" }
tonic = { version = "0.14.6", features = ["tls-ring"] }
tokio = { version = "1", features = ["full"] }
virt = "0.4"
virt-sys = "0.3.1"
anyhow = "1.0"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
phf = { version = "0.11", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tracing-appender = "0.2"
uuid = { version = "1.23.1", features = ["v4"]}
rand = "0.8"
libc = "0.2"
rcgen = {version = "0.14.7", features = ["pem", "x509-parser"] }
local-ip-address = "0.6"
tokio-stream = { version = "0.1", features = ["sync"] }
