[profile.dev]
opt-level = 0         # Disable optimizations (stops inlining)
debug = 2             # Full debug info (line tables, symbols, etc.)

[profile.dev.package."*"]
opt-level = 0         # Apply "no optimizations" to all external crates


[workspace]
resolver = "3"
members = [
  "crates/malbox-proto",
  "crates/malbox-controller",
  "crates/malbox-agent",
]


[workspace.package]
name = "Malbox"
version = "0.1.0"
edition = "2024"
authors = ["MalWhere-CU"]
license = "MIT"
