listen_addr = "0.0.0.0:8080"
[libvirt]
uri = "qemu:///system"
[paths]

master_nvram = "/home/mohamed/vm-images/master/master_vars.fd"

# master_image = "/home/mohamed/vm-images/alpine-gold.qcow2"
master_image = "/home/mohamed/vm-images/master/testmaster.qcow2"

overlay_dir = "/home/mohamed/vm-images/overlays/"

report_dir = "/home/mohamed/vm-images/reports/"

nvram_dir = "/home/mohamed/vm-images/nvrams/"
[vm]

vcpus = 2
memory_mb = 4096
